name = "sundae/contracts"
version = "0.0.0"
license = "Apache-2.0"
description = "Experimental port of SundaeSwap to Aiken"

[repository]
user = "sundae"
project = "contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "main"
source = "github"

[[dependencies]]
name = "KtorZ/tx_util"
version = "48a3e88ff3776f30133f9c3a5852f2b5163ae51e"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.16"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"
